### ISSUE TITLE
AecSdkDemo

### ISSUE THREAD

**Issue by PeadarO** [pauldotknopf/pauldotknopf.github.io#7]
I am looking at AecSdkDemo and it really is very good. I am trying to compress the output of it. I can compress it with LAME but there is an annoying delay with LAME when I send the compressed voice through a socket to another computer. I would like to use another encoder, most likely FFMPEG. Most encoders seem to need an 8 bit input.  Is there any way of getting AecSdkDemo to produce an 8 bit output?
In AecSdkDemo I have changed this......
WAVEFORMATEX wfxOut = { WAVE_FORMAT_PCM, 1, 8000, 16000, 2, 16, 0 };
to this.....
WAVEFORMATEX wfxOut = { WAVE_FORMAT_PCM, 1, 8000, 8000, 1, 8, 0 };

but the SetOutputType then returns a DMO_E_TYPE_NOT_ACCEPTED

I have downloaded a load of other programs and used their 8-bit versions of WAVEFORMATEX but they all give me the same error in AecSdkDemo.

Thanks in advance for any help

Peadar, Dublin, Ireland.

**Comment by pauldotknopf** [comment]
Umm, I think you're lost.
